version: "3.7"
services: 
  backend:
    container_name: backend
    build:
      context: . #esto es como la ruta, el punto significa que es en mismo lugar de este archivo
      dockerfile: Dockerfile
    ports: 
      - 3001:5001
    networks:
      - processor-net #nombre de la red

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001" # Especifica el puerto estático para la consola

networks:
  processor-net:
    driver: bridge
  minio-network:
